### ISSUE TITLE
Implementing PinchZoom using MicaSurfaceView

### ISSUE THREAD

**Issue by bhaumik2712** [micabytes/mica-android#2]
I am streaming video on surfaceview and I want to set pinch zoom in / out.
How can I do that using MicaSurfaceView ?

Thanks

**Comment by micabyte** [comment]
Ooh, interesting. Haven't tried anything like that before.

Basically, though, you should be able to just implement setZoom(...) in your renderer and take it from there in scaling your stream.

**Comment by bhaumik2712** [comment]
Thanks for the reply.
I will try out.
